### PR TITLE
Implement signup and login features

### PR DESCRIPTION
**Pull request by erdalzeynep**

### CODE REVIEW

**Comment by LetsDoItSD5** [comment]
Is this working?

**Comment by Mehdi-Attarpour** [comment]
Is this working???
@erdalzeynep

**Comment by Mehdi-Attarpour** [comment]
I assume it is working and I merge the pull request

**Comment by LetsDoItSD5** [comment]
[Login, Signup, Sign out](https://trello.com/c/PMCXDbhN/8-login-signup-sign-out)

**Pull request merged**
